# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: bdqnghi@gmail.com | dqnbui.2016@smu.edu.sg
description: > # this means to ignore newlines until "baseurl:"
 Nghi Bui's academic website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bdqnghi.github.com" # the base hostname & protocol for your site
future: true # allows future dated posts
jobtitle: "Ph.D in Computer Science"

#social networks
twitter_username: QuocNghi91
github_username: bdqnghi
linkedin_username: quocnghi
google_scholar_id: QwybxYsAAAAJ

# Build settings
markdown: kramdown

# Other Options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-117832171-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking